### ISSUE TITLE
Make creo2urdf export the urdf and the steps

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/study-revision-simulation-model#4]
### Task description

This is the follow-up of:
- #3 

We need to take that simulation model and try to export the urdf and the steps.

### Definition of done

We have an outcome of the exportation of the simulation model

**Comment by Nicogene** [comment]
I run `creo2urdf` on the simulation model produced by @salvi-mattia using this simple yaml:
```yaml
# Robot name
robotName: ergoCub

# Model base origin
originXYZ: [0.0,0.0,0.80]
originRPY: [0.0,0.0,0.0]
# Meshes options
scale: [0.001,0.001,0.001]
filenameformat: "package://ergoCub/meshes/simmechanics/%s.obj"
epsilon: 2e-4
exportMeshes: Yes
forcelowercase: Yes
root: chest

rename:
    # upperbody
    SIM_ECUB_1-1_CHEST: chest
    # head
    SIM_ECUB_1-1_HEAD_NECK_2: neck_2
    SIM_ECUB_1-1_HEAD_NECK_3: neck_3
    SIM_ECUB_1-1_HEAD: head
    SIM_ECUB_1-1_CHEST--SIM_ECUB_1-1_HEAD_NECK_2: neck_pitch # It will be fixed
    SIM_ECUB_1-1_HEAD_NECK_2--SIM_ECUB_1-1_HEAD_NECK_3: neck_roll
    SIM_ECUB_1-1_HEAD_NECK_3--SIM_ECUB_1-1_HEAD: neck_yaw

# Frames options
exportAllUseradded: No
linkFrames:
  # upperbody
  - linkName: chest
    frameName: SCSYS_CHEST
  # head
  - linkName: neck_2
    frameName: SCSYS_NECK_2
  - linkName: neck_3
    frameName: SCSYS_NECK_3
  - linkName: head
    frameName: SCSYS_HEAD


reverseRotationAxis:
    neck_pitch
    neck_roll


XMLBlobs:
    - |
            <link name="base_link" />
    - |
            <joint name="base_link_fixed_joint" type="fixed">
              <origin xyz="0 0 0" rpy="0 -0 0" />
              <axis xyz="0 0 0" />
              <parent link="chest" />
              <child link="base_link" />
            </joint>
```

I set `meshFormat` to `step` and in fact I manage to export a step for each part


![Image](https://github.com/user-attachments/assets/7aea50ed-c76e-4702-b54b-2b67efc1799d)


Unfortunately, when I try to open it in creo I get this

![Image](https://github.com/user-attachments/assets/5dc69824-77fc-4310-a9d7-589d5352b250)

![Image](https://github.com/user-attachments/assets/383b9f30-d7ce-45ba-add3-778c6cb32bd8)


I don't know if I am doing something wrong in opening or we need to adjust the save of the step on the creo2urdf side.


For this reason, for checking the kinematics of the URDF I moved back to the stl:

![Image](https://github.com/user-attachments/assets/bce7607b-fcb2-4c6d-b93d-089bcd1fee49)



Here is the resulting URDF

``` urdf
<?xml version="1.0"?>
<robot name="ergoCub">
  <link name="chest">
    <inertial>
      <mass value="8.446391235676916"/>
      <origin xyz="-0.03451610562391749 -4.120100748408981e-4 0.08701118778004516" rpy="0 -0 0"/>
      <inertia ixx="0.04613180845517581" ixy="4.522002151840497e-5" ixz="-0.0013832887860865672" iyy="0.05976879557790202" iyz="-1.198587487824821e-4" izz="0.042720130815142934"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 -0 0"/>
      <geometry>
        <mesh filename="package://ergoCub/meshes/simmechanics/sim_ecub_1-1_chest.obj" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 -0 0"/>
      <geometry>
        <mesh filename="package://ergoCub/meshes/simmechanics/sim_ecub_1-1_chest.obj" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </collision>
  </link>
  <joint name="neck_pitch" type="revolute">
    <origin xyz="0.004899999999999976 -8.752820143698503e-18 0.22730000000000014" rpy="8.720273390228122e-17 2.372754893649796e-17 -1.5949024941506653e-15"/>
    <axis xyz="4.439712919559238e-16 -1 -4.763903982225366e-17"/>
    <parent link="chest"/>
    <child link="neck_2"/>
    <limit lower="-0.7853981633974483" upper="0.3839724354387525" effort="1e+9" velocity="1e+9"/>
    <dynamics damping="2" friction="0"/>
  </joint>
  <link name="neck_2">
    <inertial>
      <mass value="0.2950466933335733"/>
      <origin xyz="-0.010695927048238603 -6.965741741153417e-5 0.009248881274781628" rpy="0 -0 0"/>
      <inertia ixx="1.2616321799784676e-4" ixy="1.0542198077524113e-7" ixz="8.468257110606068e-7" iyy="2.395361132688116e-4" iyz="-2.105142344769696e-7" izz="3.062848785762744e-4"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 -0 0"/>
      <geometry>
        <mesh filename="package://ergoCub/meshes/simmechanics/sim_ecub_1-1_head_neck_2.obj" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 -0 0"/>
      <geometry>
        <mesh filename="package://ergoCub/meshes/simmechanics/sim_ecub_1-1_head_neck_2.obj" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </collision>
  </link>
  <joint name="neck_roll" type="revolute">
    <origin xyz="-8.673617379884035e-19 -2.6045227715004048e-17 0.009500000000000203" rpy="6.119389527435216e-17 5.55111512313084e-17 1.5777218104420236e-30"/>
    <axis xyz="-1 3.6839140365666785e-23 -2.544934468759049e-16"/>
    <parent link="neck_2"/>
    <child link="neck_3"/>
    <limit lower="-0.3490658503988659" upper="0.3490658503988659" effort="1e+9" velocity="1e+9"/>
    <dynamics damping="2" friction="0"/>
  </joint>
  <link name="neck_3">
    <inertial>
      <mass value="0.2620328595780219"/>
      <origin xyz="-0.011293666345048105 -7.047255304677596e-6 0.04415406575767544" rpy="0 -0 0"/>
      <inertia ixx="2.1062741138446373e-4" ixy="-2.7403112333978993e-8" ixz="-8.810666691696946e-5" iyy="2.7050799445662026e-4" iyz="-8.812856718755064e-8" izz="1.0766129835227265e-4"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 -0 0"/>
      <geometry>
        <mesh filename="package://ergoCub/meshes/simmechanics/sim_ecub_1-1_head_neck_3.obj" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 -0 0"/>
      <geometry>
        <mesh filename="package://ergoCub/meshes/simmechanics/sim_ecub_1-1_head_neck_3.obj" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </collision>
  </link>
  <joint name="neck_yaw" type="revolute">
    <origin xyz="0 -3.946247865236552e-19 0.08659999999999962" rpy="3.568783746895866e-30 3.071149188790181e-19 -8.482103908136196e-14"/>
    <axis xyz="-3.450576611009997e-19 3.590217307363154e-30 0.9999999999999991"/>
    <parent link="neck_3"/>
    <child link="head"/>
    <limit lower="-0.7853981633974483" upper="0.7853981633974483" effort="1e+9" velocity="1e+9"/>
    <dynamics damping="2" friction="0"/>
  </joint>
  <link name="head">
    <inertial>
      <mass value="1.6877537891559422"/>
      <origin xyz="-0.00579684251407986 -0.0014063303319488333 0.0284992584997088" rpy="0 -0 0"/>
      <inertia ixx="0.00766140941485117" ixy="-9.460416353458076e-6" ixz="7.186768988995472e-5" iyy="0.008648699527808213" iyz="6.245019892637198e-6" izz="0.006995785045702638"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 -0 0"/>
      <geometry>
        <mesh filename="package://ergoCub/meshes/simmechanics/sim_ecub_1-1_head.obj" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 -0 0"/>
      <geometry>
        <mesh filename="package://ergoCub/meshes/simmechanics/sim_ecub_1-1_head.obj" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </collision>
  </link>
  <link name="base_link"/>
  <joint name="base_link_fixed_joint" type="fixed">  <origin xyz="0 0 0" rpy="0 -0 0"/>  <axis xyz="0 0 0"/>  <parent link="chest"/>  <child link="base_link"/></joint>
  <gazebo>
    <pose>0.000000 0.000000 0.800000 0.000000 0.000000 0.000000</pose>
  </gazebo>
</robot>


```

cc @supermonkey-design @pillai-s @salvi-mattia @fiorisi @traversaro
